#### Imports (임포트)

지금까지는 Python 언어 자체에 내장된 타입과 함수들만 다뤘습니다.
하지만 Python의 가장 큰 장점 중 하나는(특히 데이터 사이언스 분야에서) 매우 수준 높은 외부 라이브러리들이 엄청나게 많다는 점입니다.
이 라이브러리들 중 일부는 표준 라이브러리(Standard Library) 에 포함되어 있어서 Python이 설치된 어디서든 사용할 수 있습니다.
또 어떤 라이브러리들은 기본 포함은 아니지만 쉽게 추가 설치할 수 있습니다.
이러한 코드들을 사용하기 위해 우리는 import(임포트) 를 사용합니다.

```python
import math
print("It's math! It has type {}".format(type(math)))
```

출력:
```python
It's math! It has type <class 'module'>
```

math는 모듈(module) 입니다.
모듈은 다른 사람이 정의해 둔 변수들의 집합(네임스페이스)이라고 생각하면 됩니다.
dir() 함수를 사용하면 모듈 안에 어떤 이름들이 들어있는지 볼 수 있습니다.

```python
print(dir(math))
```

#### 모듈 안의 값 사용하기

모듈 안의 변수는 .(dot) 문법으로 접근합니다.

예를 들어 math.pi:
```python
print("pi to 4 significant digits = {:.4}".format(math.pi))
```

출력:
```python
pi to 4 significant digits = 3.142
```

대부분은 함수입니다. 예를 들어 math.log:
```python
math.log(32, 2)
```

출력:
```python
5.0
```

#### help() 함수

함수가 뭔지 모르겠다면 help()를 사용할 수 있습니다.

```python
help(math.log)
```

설명:
```python
log(x, [base=math.e])
x의 로그값 반환
base를 지정하지 않으면 자연로그(e 기반) 반환
```

모듈 전체에 대해서도 help(math)를 사용할 수 있습니다.

#### 다른 import 문법
#### 별칭(alias) 사용하기

```python
import math as mt
```

이제:
```python
mt.pi
```
처럼 사용할 수 있습니다.
데이터 분석에서는 이런 관례가 많습니다.

예:
```python
import numpy as np
import pandas as pd
```

as는 단순히 이름을 바꾸는 것입니다.

즉:
```python
mt = math
```
와 거의 같습니다.

```python
from ... import ...
from math import *
```

이렇게 하면:
```python
print(pi, log(32, 2))
```
처럼 math. 없이 바로 사용할 수 있습니다.

하지만 문제점도 있음
```python
from math import *
from numpy import *
```

이후:
```python
log(32, 2)
```
를 실행하면 오류가 발생합니다.

왜냐하면:
* math에도 log 함수가 있고
* numpy에도 log 함수가 있음

그런데 나중에 import한 numpy.log가 기존 math.log를 덮어써버렸기 때문입니다.
이걸 shadowing(가려짐) 이라고 합니다.

#### 좋은 방법

필요한 것만 가져오기:
```python
from math import log, pi
from numpy import asarray
```

#### Submodule(하위 모듈)

모듈 안에는 또 다른 모듈이 들어있을 수 있습니다.

예:
```python
import numpy
numpy.random
```
은 numpy 안의 하위 모듈입니다.

예시: 주사위 10번 굴리기
```python
rolls = numpy.random.randint(low=1, high=6, size=10)
```

예시 출력:
```python
array([3, 4, 3, 4, 5, 5, 2, 1, 3, 3])
```

#### 새로운 객체 타입들

Python 기본 타입만 있는 게 아닙니다.
라이브러리들은 자신만의 타입을 만듭니다.

예:
* matplotlib → Figure, Subplot
* pandas → DataFrame, Series
* numpy → ndarray

#### 낯선 객체를 이해하는 3가지 도구
#### 1. type()

“이게 뭐지?”

```python
type(rolls)
```

출력:
```python
numpy.ndarray
```

#### 2. dir()

“무슨 기능이 있지?”

```python
dir(rolls)
```
여러 메서드들이 나옵니다.

예:
```python
rolls.mean()
```

평균 계산:
```python
3.3
```

또는:
```python
rolls.tolist()
```

리스트로 변환:
```python
[3, 4, 3, 4, 5, 5, 2, 1, 3, 3]
```

#### 3. help()

“이 기능 자세히 알려줘”

```python
help(rolls.ravel)
```

설명:
```python
배열을 1차원으로 펼쳐준다(flatten)
```

#### Operator Overloading (연산자 오버로딩)
#### 일반 리스트

```python
[3,4,1] + 10
```

오류 발생:
```python
TypeError
```
왜냐하면 리스트 + 숫자는 불가능하기 때문입니다.

#### numpy 배열은 다름

```python
rolls + 10
```

출력:
```python
array([13,14,13,...])
```
numpy는 + 연산을 각 원소에 적용하도록 정의했기 때문입니다.

#### 비교 연산도 다르게 동작

```python
rolls <= 3
```

출력:
```python
array([True, False, True, ...])
```
각 원소별 비교 결과를 반환합니다.

#### 다차원 배열 인덱싱

```python
x[1,-1]
```

출력:
```python
6
```
numpy는 (행, 열) 형태 인덱싱 지원.

하지만 일반 리스트는:
```python
xlist[1,-1]
```
오류 발생.

#### TensorFlow의 더 신기한 예시

```python
a + b
```

결과가 단순 숫자 2가 아니라:
```python
<tf.Tensor ...>
```
TensorFlow는 연산 자체를 “계산 그래프”로 다루기 때문입니다.
즉, 라이브러리마다 연산자의 의미를 새롭게 정의할 수 있습니다.

#### pandas 예시

```python
df[(df['population'] > 10**6) &
   (df['continent'] == 'South America')]
```

이 코드도 사실:
* >
* ==
* &
* []
같은 연산자들이 모두 오버로딩된 결과입니다.

#### double underscore 메서드

dir(list)를 보면:
```python
'__add__'
'__contains__'
'__getitem__'
```
같은 것들이 보입니다.
이들은 Python이 특별하게 사용하는 메서드입니다.

예를 들어:
```python
x in [1,2,3]
```

은 실제로는:
```python
[1,2,3].__contains__(x)
```
를 호출하는 것입니다.